// Format: { id, quote, character, manga, category, aliases[] }
// category: "shonen" | "shojo" | "seinen"
// aliases: other accepted spellings / shortened names

module.exports = [
  // ── SHONEN ────────────────────────────────────────────────────────
  {
    id: 1,
    quote: "Je ne recule jamais et je ne regrette rien !",
    character: "Naruto Uzumaki",
    manga: "Naruto",
    category: "shonen",
    aliases: ["naruto"],
  },
  {
    id: 2,
    quote: "Je deviendrai Hokage, c'est ma promesse et ma voie ninja !",
    character: "Naruto Uzumaki",
    manga: "Naruto",
    category: "shonen",
    aliases: ["naruto"],
  },
  {
    id: 3,
    quote: "Ceux qui abandonnent leurs coéquipiers sont pires que des ordures.",
    character: "Kakashi Hatake",
    manga: "Naruto",
    category: "shonen",
    aliases: ["kakashi"],
  },
  {
    id: 4,
    quote: "Pardonne-moi, Sasuke. C'est la dernière fois.",
    character: "Itachi Uchiha",
    manga: "Naruto",
    category: "shonen",
    aliases: ["itachi"],
  },
  {
    id: 5,
    quote: "Jusqu'à ce que tu rouvres les yeux, je ne mourrai pas.",
    character: "Jiraiya",
    manga: "Naruto",
    category: "shonen",
    aliases: ["jiraya", "jiraia"],
  },
  {
    id: 6,
    quote: "Je suis uniquement mû par la haine.",
    character: "Sasuke Uchiha",
    manga: "Naruto",
    category: "shonen",
    aliases: ["sasuke"],
  },
  {
    id: 7,
    quote: "Si tu abandonnes tes rêves, tu mourras debout.",
    character: "Rock Lee",
    manga: "Naruto",
    category: "shonen",
    aliases: ["lee", "rock lee"],
  },
  {
    id: 8,
    quote: "Je deviendrai le Roi des Pirates !",
    character: "Monkey D. Luffy",
    manga: "One Piece",
    category: "shonen",
    aliases: ["luffy", "monkey luffy"],
  },
  {
    id: 9,
    quote: "Je n'ai jamais demandé à être sauvé. C'est moi qui choisis mes combats.",
    character: "Roronoa Zoro",
    manga: "One Piece",
    category: "shonen",
    aliases: ["zoro"],
  },
  {
    id: 10,
    quote: "Je suis heureux d'être né. Merci de m'avoir aimé.",
    character: "Portgas D. Ace",
    manga: "One Piece",
    category: "shonen",
    aliases: ["ace", "portgas ace"],
  },
  {
    id: 11,
    quote: "J'ai envie de vivre ! Moi aussi, j'ai le droit d'exister dans ce monde !",
    character: "Nico Robin",
    manga: "One Piece",
    category: "shonen",
    aliases: ["robin", "nico robin"],
  },
  {
    id: 12,
    quote: "Je suis le plus grand ! Un Saiyen né pour se battre !",
    character: "Son Goku",
    manga: "Dragon Ball Z",
    category: "shonen",
    aliases: ["goku", "sangoku", "kakarot"],
  },
  {
    id: 13,
    quote: "Je suis le prince des Saiyens, le plus fier de tout l'univers !",
    character: "Vegeta",
    manga: "Dragon Ball Z",
    category: "shonen",
    aliases: ["vegeta"],
  },
  {
    id: 14,
    quote: "Ne blessez pas mes amis. Sinon, je ne me retiendrai plus.",
    character: "Son Gohan",
    manga: "Dragon Ball Z",
    category: "shonen",
    aliases: ["gohan"],
  },
  {
    id: 15,
    quote: "Je vais exterminer tous les titans jusqu'au dernier !",
    character: "Eren Yeager",
    manga: "L'Attaque des Titans",
    category: "shonen",
    aliases: ["eren", "yeager", "jager"],
  },
  {
    id: 16,
    quote: "Abandonne sans regrets ou meurs sans regrets. C'est tout ce que tu peux faire.",
    character: "Levi Ackerman",
    manga: "L'Attaque des Titans",
    category: "shonen",
    aliases: ["levi"],
  },
  {
    id: 17,
    quote: "Ceux qui ne renoncent à rien ne peuvent rien changer.",
    character: "Armin Arlert",
    manga: "L'Attaque des Titans",
    category: "shonen",
    aliases: ["armin"],
  },
  {
    id: 18,
    quote: "Je vais devenir le plus grand héros ! C'est mon destin.",
    character: "Izuku Midoriya",
    manga: "My Hero Academia",
    category: "shonen",
    aliases: ["deku", "midoriya", "izuku"],
  },
  {
    id: 19,
    quote: "Je viens toujours ! C'est pourquoi je suis toujours là !",
    character: "All Might",
    manga: "My Hero Academia",
    category: "shonen",
    aliases: ["all might", "allmight"],
  },
  {
    id: 20,
    quote: "Je gagnerai. Toujours. Je serai le numéro un.",
    character: "Katsuki Bakugo",
    manga: "My Hero Academia",
    category: "shonen",
    aliases: ["bakugo", "bakugou", "katsuki"],
  },
  {
    id: 21,
    quote: "Peu importe combien de fois tu es blessé, garde la chaleur dans ton cœur.",
    character: "Tanjiro Kamado",
    manga: "Demon Slayer",
    category: "shonen",
    aliases: ["tanjiro", "kamado"],
  },
  {
    id: 22,
    quote: "Je suis lâche, mais quand il s'agit de mes amis, je ne recule jamais !",
    character: "Zenitsu Agatsuma",
    manga: "Demon Slayer",
    category: "shonen",
    aliases: ["zenitsu", "agatsuma"],
  },
  {
    id: 23,
    quote: "Mets le feu en ton cœur et avance. C'est la façon de vivre des Rengoku !",
    character: "Rengoku Kyojuro",
    manga: "Demon Slayer",
    category: "shonen",
    aliases: ["rengoku", "kyojuro"],
  },
  {
    id: 24,
    quote: "Je suis le plus fort. Partout. Tout le temps.",
    character: "Gojo Satoru",
    manga: "Jujutsu Kaisen",
    category: "shonen",
    aliases: ["gojo", "satoru"],
  },
  {
    id: 25,
    quote: "Je veux mourir entouré de gens, après avoir vu de nombreuses choses.",
    character: "Yuji Itadori",
    manga: "Jujutsu Kaisen",
    category: "shonen",
    aliases: ["itadori", "yuji"],
  },
  {
    id: 26,
    quote: "Je ne sais pas comment, mais je le ferai quand même !",
    character: "Gon Freecss",
    manga: "Hunter x Hunter",
    category: "shonen",
    aliases: ["gon", "freecss"],
  },
  {
    id: 27,
    quote: "Si tu dois tuer quelqu'un, dis-le-moi. Je le ferai à ta place.",
    character: "Killua Zoldyck",
    manga: "Hunter x Hunter",
    category: "shonen",
    aliases: ["killua", "zoldyck"],
  },
  {
    id: 28,
    quote: "Un humain qui ne peut rien sacrifier ne peut rien changer.",
    character: "Edward Elric",
    manga: "Fullmetal Alchemist",
    category: "shonen",
    aliases: ["edward", "elric", "ed"],
  },
  {
    id: 29,
    quote: "Ce pays sera le mien, et personne ne pourra l'arrêter.",
    character: "Roy Mustang",
    manga: "Fullmetal Alchemist",
    category: "shonen",
    aliases: ["mustang", "roy"],
  },
  {
    id: 30,
    quote: "Ce monde est pourri. Il faut le purifier, moi seul peux le faire.",
    character: "Light Yagami",
    manga: "Death Note",
    category: "shonen",
    aliases: ["light", "yagami", "kira"],
  },
  {
    id: 31,
    quote: "Les humains sont des créatures qui finissent par mentir, même à eux-mêmes.",
    character: "L Lawliet",
    manga: "Death Note",
    category: "shonen",
    aliases: ["l", "lawliet", "ryuzaki"],
  },
  {
    id: 32,
    quote: "Je ne me bats pas pour conquérir. Je me bats pour protéger ceux qui me sont chers.",
    character: "Ichigo Kurosaki",
    manga: "Bleach",
    category: "shonen",
    aliases: ["ichigo", "kurosaki"],
  },
  {
    id: 33,
    quote: "J'ai évolué au-delà du simple stade de capitaine, de la Gotei 13 et même du Soul Society.",
    character: "Sosuke Aizen",
    manga: "Bleach",
    category: "shonen",
    aliases: ["aizen", "sosuke"],
  },
  {
    id: 34,
    quote: "Je suis héros juste parce que j'en avais envie. C'est tout.",
    character: "Saitama",
    manga: "One Punch Man",
    category: "shonen",
    aliases: ["saitama", "one punch man"],
  },
  {
    id: 35,
    quote: "Je vais surpasser mes limites et devenir le disciple digne de Sensei.",
    character: "Genos",
    manga: "One Punch Man",
    category: "shonen",
    aliases: ["genos"],
  },
  {
    id: 36,
    quote: "Je ne veux pas perdre ce qui compte pour moi. C'est pour ça que je me bats !",
    character: "Natsu Dragneel",
    manga: "Fairy Tail",
    category: "shonen",
    aliases: ["natsu", "dragneel"],
  },
  {
    id: 37,
    quote: "Je n'ai pas de magie à ma naissance, mais je deviendrai quand même Roi des Mages !",
    character: "Asta",
    manga: "Black Clover",
    category: "shonen",
    aliases: ["asta"],
  },
  {
    id: 38,
    quote: "Je volerai dans les airs une fois de plus !",
    character: "Shoyo Hinata",
    manga: "Haikyuu",
    category: "shonen",
    aliases: ["hinata", "shoyo"],
  },
  {
    id: 39,
    quote: "Je te mettrai en valeur. Je suis le seul à pouvoir le faire.",
    character: "Tobio Kageyama",
    manga: "Haikyuu",
    category: "shonen",
    aliases: ["kageyama", "tobio"],
  },
  {
    id: 40,
    quote: "Je n'aime pas gagner ni perdre. Ce que j'aime, c'est juste jouer.",
    character: "Kozume Kenma",
    manga: "Haikyuu",
    category: "shonen",
    aliases: ["kenma", "kozume"],
  },
  {
    id: 41,
    quote: "Même si je meurs, je ne te laisserai pas faire du mal à mes amis.",
    character: "Alphonse Elric",
    manga: "Fullmetal Alchemist",
    category: "shonen",
    aliases: ["alphonse", "al"],
  },
  {
    id: 42,
    quote: "Les humains m'ont toujours semblé si intéressants.",
    character: "Ryuk",
    manga: "Death Note",
    category: "shonen",
    aliases: ["ryuk", "ryuuku"],
  },
  {
    id: 43,
    quote: "Le travail, c'est ce qui s'oppose à ce qui a vraiment de la valeur dans la vie.",
    character: "Kento Nanami",
    manga: "Jujutsu Kaisen",
    category: "shonen",
    aliases: ["nanami", "kento"],
  },
  {
    id: 44,
    quote: "Si tu veux me tuer, déteste-moi. Vis dans la honte et continue de survivre.",
    character: "Itachi Uchiha",
    manga: "Naruto",
    category: "shonen",
    aliases: ["itachi"],
  },
  {
    id: 45,
    quote: "Mon rêve transcende le temps et l'espace. Je l'atteindrai.",
    character: "Griffith",
    manga: "Berserk",
    category: "shonen",
    aliases: ["griffith", "femto"],
  },

  // ── SHOJO ─────────────────────────────────────────────────────────
  {
    id: 46,
    quote: "Je suis la guerrière de l'amour et de la justice ! Je suis Sailor Moon !",
    character: "Sailor Moon",
    manga: "Sailor Moon",
    category: "shojo",
    aliases: ["usagi", "usagi tsukino", "bunny"],
  },
  {
    id: 47,
    quote: "Je n'ai encore jamais rencontré quelqu'un d'absolument inutile.",
    character: "Tohru Honda",
    manga: "Fruits Basket",
    category: "shojo",
    aliases: ["tohru", "honda"],
  },
  {
    id: 48,
    quote: "Tout ce qui est vraiment précieux finit par nous être arraché.",
    character: "Nana Osaki",
    manga: "Nana",
    category: "shojo",
    aliases: ["nana", "osaki"],
  },
  {
    id: 49,
    quote: "Tout ira bien, j'en suis certaine !",
    character: "Sakura Kinomoto",
    manga: "Cardcaptor Sakura",
    category: "shojo",
    aliases: ["sakura", "kinomoto"],
  },
  {
    id: 50,
    quote: "Je veux te voir sourire. C'est la seule chose que je désire.",
    character: "Tamaki Suoh",
    manga: "Ouran High School Host Club",
    category: "shojo",
    aliases: ["tamaki", "suoh"],
  },
  {
    id: 51,
    quote: "Les gens qui souffrent ont besoin d'amour, pas de pitié.",
    character: "Tohru Honda",
    manga: "Fruits Basket",
    category: "shojo",
    aliases: ["tohru", "honda"],
  },
  {
    id: 52,
    quote: "Je courrai aussi vite que mes jambes me le permettront pour être près de toi.",
    character: "Sawako Kuronuma",
    manga: "Kimi ni Todoke",
    category: "shojo",
    aliases: ["sawako", "kuronuma"],
  },
  {
    id: 53,
    quote: "La force n'est pas tout. Ce qui importe, c'est la façon dont tu te relèves.",
    character: "Yona",
    manga: "Yona of the Dawn",
    category: "shojo",
    aliases: ["yona"],
  },

  // ── SEINEN ────────────────────────────────────────────────────────
  {
    id: 54,
    quote: "Dans ce monde, la souffrance et la mort accompagnent toujours ceux qui poursuivent leurs rêves.",
    character: "Guts",
    manga: "Berserk",
    category: "seinen",
    aliases: ["guts", "le guerrier noir"],
  },
  {
    id: 55,
    quote: "Je ne voulais pas être un monstre. Mais je ne pouvais plus rester humain.",
    character: "Ken Kaneki",
    manga: "Tokyo Ghoul",
    category: "seinen",
    aliases: ["kaneki", "ken kaneki"],
  },
  {
    id: 56,
    quote: "Vivre, c'est blesser les autres ou être blessé. Il n'y a pas d'autre choix.",
    character: "Touka Kirishima",
    manga: "Tokyo Ghoul",
    category: "seinen",
    aliases: ["touka", "kirishima"],
  },
  {
    id: 57,
    quote: "Il n'y a pas d'ennemis. Il n'y a pas de vraie bataille. Il n'y a pas de roi en ce monde.",
    character: "Askeladd",
    manga: "Vinland Saga",
    category: "seinen",
    aliases: ["askeladd"],
  },
  {
    id: 58,
    quote: "Un vrai guerrier n'a pas besoin d'une épée.",
    character: "Thorfinn",
    manga: "Vinland Saga",
    category: "seinen",
    aliases: ["thorfinn"],
  },
  {
    id: 59,
    quote: "La plus grande victoire est de se vaincre soi-même.",
    character: "Miyamoto Musashi",
    manga: "Vagabond",
    category: "seinen",
    aliases: ["musashi", "miyamoto"],
  },
  {
    id: 60,
    quote: "Je ne fais qu'apprécier la vie à ma façon. Je ne cherche pas de sens à tout ça.",
    character: "Spike Spiegel",
    manga: "Cowboy Bebop",
    category: "seinen",
    aliases: ["spike", "spiegel"],
  },
  {
    id: 61,
    quote: "L'homme qui tient son épée sans chercher le combat est le plus dangereux de tous.",
    character: "Guts",
    manga: "Berserk",
    category: "seinen",
    aliases: ["guts"],
  },
  {
    id: 62,
    quote: "Personne ne peut choisir où il naît. Mais on peut choisir comment on meurt.",
    character: "Ken Kaneki",
    manga: "Tokyo Ghoul",
    category: "seinen",
    aliases: ["kaneki", "ken kaneki"],
  },
];
