const classementQuestions = {
  manga: [
    "Un héros de Dragon Ball",
    "Un méchant de Naruto",
    "Une waifu de One Piece",
    "Un arc de Hunter x Hunter",
    "Un Hokage de Konoha",
    "Un capitaine de la Soul Society",
    "Un démon dans Demon Slayer",
    "Un Pilier dans Demon Slayer",
    "Un Titan dans Attack on Titan",
    "Un personnage de Fullmetal Alchemist",
    "Un Stand de Jojo's Bizarre Adventure",
    "Un Fruit du Démon",
    "Une technique de combat de Naruto",
    "Un personnage de My Hero Academia",
    "Un Quirk dans MHA",
    "Un personnage de Death Note",
    "Un Pokémon de première génération",
    "Une attaque spéciale dans Dragon Ball",
    "Un personnage de One Punch Man",
    "Un Arrancar dans Bleach",
    "Un personnage de Jujutsu Kaisen",
    "Un sorcier maudit dans JJK",
    "Un membre des Mugiwaras",
    "Un arc d'One Piece",
    "Un personnage de Re:Zero",
    "Un personnage de Fairy Tail",
    "Un personnage de Black Clover",
    "Un protagoniste de Vinland Saga",
    "Un démon dans Chainsaw Man",
    "Un personnage de Dr. Stone",
    "Un antagoniste de Dragon Ball",
    "Un personnage de Hunter x Hunter",
    "Un personnage de Code Geass",
    "Un personnage de Cowboy Bebop",
    "Un kage dans Naruto",
    "Un personnage d'Overlord",
    "Un personnage de Sword Art Online",
    "Un ennemi dans Attack on Titan",
    "Un personnage de Tokyo Ghoul",
    "Un personnage de Mob Psycho 100",
  ],

  cinema: [
    "Un film de la saga Marvel",
    "Un film de Christopher Nolan",
    "Un film de Quentin Tarantino",
    "Un film de Steven Spielberg",
    "Un film Star Wars",
    "Un film Disney classique",
    "Un film Pixar",
    "Un acteur hollywoodien",
    "Une actrice hollywoodienne",
    "Un méchant de cinéma",
    "Un super-héros au cinéma",
    "Un film d'horreur culte",
    "Un film de science-fiction",
    "Un film d'action des années 90",
    "Un film romantique",
    "Un film français primé",
    "Un film James Bond",
    "Un personnage de Harry Potter",
    "Un film du Seigneur des Anneaux",
    "Un film d'animation Studio Ghibli",
    "Un film de Tim Burton",
    "Un réalisateur légendaire",
    "Un film de guerre",
    "Un film primé aux Oscars",
    "Un film de la saga Fast & Furious",
    "Un personnage iconique de cinéma",
    "Un film de comédie américaine",
    "Un film d'espionnage",
    "Un film de western",
    "Un film de gangsters",
    "Un film d'aventure",
    "Un acteur français connu à Hollywood",
    "Un film de la saga Jurassic Park",
    "Un film d'animation DreamWorks",
    "Un film culte des années 80",
    "Une saga cinématographique",
    "Un film de robots ou d'IA",
    "Un film de DC Comics",
    "Un film de zombies",
    "Un remake célèbre",
  ],

  geographie: [
    "Un pays d'Afrique subsaharienne",
    "Un pays d'Asie de l'Est",
    "Une capitale européenne",
    "Un fleuve d'Europe",
    "Une montagne dans les Alpes",
    "Un pays d'Amérique du Sud",
    "Un désert dans le monde",
    "Un pays du Moyen-Orient",
    "Une ville des États-Unis",
    "Une ville de France hors Paris",
    "Un pays d'Europe de l'Est",
    "Un pays nordique",
    "Un volcan actif dans le monde",
    "Un lac dans le monde",
    "Un pays d'Asie du Sud-Est",
    "Une chaîne de montagnes",
    "Un pays insulaire",
    "Un pays d'Océanie",
    "Une rivière de France",
    "Un pays frontalier de la France",
    "Un pays d'Afrique du Nord",
    "Une ville d'Amérique du Sud",
    "Un pays d'Amérique centrale",
    "Un détroit ou un canal maritime",
    "Un pays producteur de pétrole",
    "Une mer intérieure ou semi-fermée",
    "Un pays d'Europe du Sud",
    "Un cap géographique célèbre",
    "Un archipel dans l'Atlantique",
    "Un pays anglophone",
    "Un pays hispanophone",
    "Une ville portuaire mondiale",
    "Un pays enclavé sans accès à la mer",
    "Une péninsule dans le monde",
    "Une ville hôte des Jeux Olympiques d'été",
    "Un pays à plus de 100 millions d'habitants",
    "Un glacier ou calotte glaciaire",
    "Un pays de la péninsule ibérique",
    "Un pays des Balkans",
    "Un territoire d'outre-mer français",
  ],

  personnalites: [
    "Un inventeur célèbre",
    "Un prix Nobel de physique",
    "Un artiste peintre",
    "Un écrivain français",
    "Un philosophe grec antique",
    "Un président américain",
    "Un explorateur historique",
    "Un physicien théorique",
    "Un entrepreneur milliardaire",
    "Un militant des droits civiques",
    "Un leader révolutionnaire",
    "Un musicien classique",
    "Un acteur oscarisé",
    "Un footballeur légendaire",
    "Un athlète olympique",
    "Un cinéaste influent",
    "Un biologiste évolutionniste",
    "Un mathématicien historique",
    "Une femme de pouvoir politique",
    "Un architecte mondialement connu",
    "Un penseur du XXe siècle",
    "Un chef d'État africain marquant",
    "Un écrivain de science-fiction",
    "Un romancier du XIXe siècle",
    "Un compositeur du XXe siècle",
    "Un militant pour l'environnement",
    "Un astronaute célèbre",
    "Un pionnier de l'informatique",
    "Un couturier ou styliste de renom",
    "Un peintre impressionniste",
    "Un poète universel",
    "Un économiste influent",
    "Un chef militaire historique",
    "Une personnalité humanitaire",
    "Un acteur de comédie légendaire",
    "Un photographe légendaire",
    "Un danseur ou chorégraphe mondial",
    "Un chef de la Renaissance",
    "Un sultan ou calife historique",
    "Un souverain conquérant",
  ],

  histoire: [
    "Une bataille historique",
    "Un empire disparu",
    "Un traité de paix célèbre",
    "Une révolution dans le monde",
    "Un dirigeant militaire de l'Antiquité",
    "Un pharaon d'Égypte",
    "Un roi de France",
    "Une reine d'Europe",
    "Un événement de la Première Guerre mondiale",
    "Un événement de la Seconde Guerre mondiale",
    "Une découverte géographique",
    "Un philosophe des Lumières",
    "Une civilisation antique",
    "Un empire colonial",
    "Un personnage de la Révolution française",
    "Un pape influent dans l'histoire",
    "Une invention du XIXe siècle",
    "Un mouvement de résistance",
    "Un génocide reconnu",
    "Une crise diplomatique du XXe siècle",
    "Un accord de paix historique",
    "Une épidémie ou pandémie historique",
    "Un mouvement d'indépendance",
    "Un conflit de la Guerre froide",
    "Un blocus ou siège historique",
    "Une constitution célèbre",
    "Un régime totalitaire du XXe siècle",
    "Un procès historique",
    "Un mur ou frontière historique",
    "Un naufrage ou catastrophe maritime",
    "Une famine historique",
    "Un traité de commerce colonial",
    "Un schisme religieux",
    "Une réforme religieuse",
    "Un mouvement d'émancipation féminine",
    "Une loi abolitionniste",
    "Un soulèvement populaire",
    "Un exil politique célèbre",
    "Un attentat ayant changé l'histoire",
    "Un armistice ou cessez-le-feu",
  ],

  jeuxvideo: [
    "Un jeu de la Nintendo Switch",
    "Un FPS légendaire",
    "Un jeu de rôle japonais (JRPG)",
    "Un personnage de jeu de combat",
    "Un jeu de la franchise Zelda",
    "Un personnage de la saga Mario",
    "Un jeu de course",
    "Un jeu de stratégie en temps réel",
    "Un jeu de survie",
    "Un jeu multijoueur en ligne",
    "Un jeu indépendant (indie)",
    "Un méchant de jeu vidéo",
    "Un héros de jeu vidéo",
    "Un jeu de plateforme",
    "Un jeu d'horreur",
    "Un jeu de la saga Final Fantasy",
    "Un jeu de sport",
    "Un jeu de la PlayStation 1",
    "Un jeu de la franchise Pokémon",
    "Un boss final mémorable",
    "Un jeu de la saga Halo",
    "Un jeu d'open world",
    "Un jeu de la saga Dark Souls",
    "Un personnage de Super Smash Bros",
    "Une console de jeu",
    "Un jeu de baston ou versus fighting",
    "Un jeu de simulation",
    "Un jeu de la saga Assassin's Creed",
    "Un jeu mobile populaire",
    "Un jeu de la franchise GTA",
    "Un jeu de la franchise Resident Evil",
    "Un jeu de musique ou rythme",
    "Un jeu cyberpunk ou futuriste",
    "Un personnage de League of Legends",
    "Un jeu de la franchise Metal Gear",
    "Un MMORPG populaire",
    "Un jeu de la franchise Mortal Kombat",
    "Un jeu de la Sega Mega Drive",
    "Un jeu de la saga The Witcher",
    "Un jeu de la saga Diablo",
  ],

  gastronomie: [
    "Un fromage français",
    "Un plat de la cuisine italienne",
    "Un dessert japonais",
    "Une pâtisserie française",
    "Un plat de street food asiatique",
    "Un grand vin de Bordeaux",
    "Un cocktail célèbre",
    "Une spécialité régionale française",
    "Un plat de la cuisine mexicaine",
    "Un fruit exotique",
    "Un poisson préparé en gastronomie",
    "Une épice utilisée en cuisine",
    "Un dessert américain",
    "Un plat de la cuisine indienne",
    "Une bière du monde",
    "Un chef étoilé français",
    "Un plat de la cuisine espagnole",
    "Une sauce classique de la cuisine française",
    "Un plat de la cuisine libanaise",
    "Un champignon culinaire",
    "Un fruit de mer préparé en gastronomie",
    "Une huile utilisée en cuisine",
    "Un plat de la cuisine japonaise",
    "Un gâteau régional français",
    "Un plat de la cuisine marocaine",
    "Un petit-déjeuner du monde",
    "Un condiment mondial",
    "Un plat de la cuisine thaïlandaise",
    "Un thé du monde",
    "Un plat de la cuisine grecque",
    "Un sandwich iconique",
    "Un plat de la cuisine coréenne",
    "Une charcuterie du monde",
    "Un plat de la cuisine péruvienne",
    "Un fromage d'un autre pays que la France",
    "Un chocolat d'origine",
    "Un plat végétarien du monde",
    "Un légume utilisé en cuisine gastronomique",
    "Un apéritif ou digestif",
    "Un plat de la cuisine portugaise",
  ],

  musique: [
    "Un tube des années 80",
    "Un artiste de hip-hop américain",
    "Un groupe de rock britannique",
    "Une chanson de Michael Jackson",
    "Un album légendaire",
    "Un festival de musique mondial",
    "Un compositeur classique",
    "Un instrument à cordes",
    "Un artiste de musique électronique",
    "Une chanteuse de pop internationale",
    "Un rappeur français",
    "Un genre musical né aux États-Unis",
    "Une comédie musicale de Broadway",
    "Un guitariste légendaire",
    "Un groupe de la Motown",
    "Un DJ de renommée mondiale",
    "Un groupe de métal",
    "Un opéra célèbre",
    "Un artiste reggae",
    "Un morceau de musique de film",
    "Un pianiste classique du XXe siècle",
    "Un artiste de soul américain",
    "Un groupe de K-pop",
    "Un artiste de jazz légendaire",
    "Un instrument à vent",
    "Un duo musical célèbre",
    "Un artiste de country américaine",
    "Un concours de musique international",
    "Un artiste de bossa nova",
    "Un groupe de punk rock",
    "Une ballade romantique célèbre",
    "Un morceau de musique classique reconnaissable",
    "Un groupe de blues américain",
    "Un artiste de musique africaine mondiale",
    "Une chanson de film Disney",
    "Un batteur légendaire",
    "Un rappeur des années 90",
    "Un groupe de britpop",
    "Un artiste de variété française",
    "Un violoniste de renommée mondiale",
  ],

  sport: [
    "Un club de football européen",
    "Un joueur de tennis Grand Chelem",
    "Un champion olympique en athlétisme",
    "Un coureur cycliste du Tour de France",
    "Un nageur de compétition",
    "Un joueur de basketball NBA",
    "Un club de rugby",
    "Un boxeur champion du monde",
    "Un pilote de Formule 1",
    "Un stade légendaire",
    "Un footballeur Ballon d'Or",
    "Un pays organisateur de Coupe du Monde",
    "Un sportif français médaillé olympique",
    "Un joueur de golf professionnel",
    "Un athlète de décathlon",
    "Un judoka de compétition",
    "Un joueur de hockey sur glace",
    "Un skieur alpin",
    "Un handballeur de niveau mondial",
    "Un sport de combat",
    "Un sport collectif aux Jeux Olympiques",
    "Un équipementier sportif",
    "Un entraîneur de football légendaire",
    "Un tournoi de tennis",
    "Un lancer en athlétisme",
    "Un sport de raquette",
    "Un marathon du monde",
    "Un sport de glace",
    "Un sport nautique",
    "Une équipe nationale de football emblématique",
    "Un sport de précision",
    "Un skateboard ou sport urbain",
    "Un sport équestre",
    "Un joueur de volley-ball",
    "Un sport de salle",
    "Un sport de montagne",
    "Un joueur de cricket mondial",
    "Un sport de raquette autre que le tennis",
    "Un surfeur professionnel",
    "Un champion de MMA ou arts martiaux",
  ],

  science: [
    "Un élément du tableau périodique",
    "Un phénomène astronomique",
    "Une théorie physique",
    "Un organe du corps humain",
    "Une planète du système solaire",
    "Un animal en voie d'extinction",
    "Un lauréat du prix Nobel de médecine",
    "Une maladie infectieuse",
    "Un type d'énergie renouvelable",
    "Un instrument de mesure scientifique",
    "Une particule subatomique",
    "Un biome terrestre",
    "Un vaccin historique",
    "Un satellite artificiel",
    "Un mammifère marin",
    "Un insecte pollinisateur",
    "Un type de roche géologique",
    "Un phénomène météorologique",
    "Un cristal ou minéral",
    "Un modèle cosmologique",
    "Un type de radiation",
    "Un neurotransmetteur",
    "Un organe sensoriel",
    "Une hormone humaine",
    "Un type de cellule sanguine",
    "Un type de nuage",
    "Un paradoxe scientifique ou mathématique",
    "Un fossile préhistorique",
    "Un type de symbiose",
    "Un biome océanique",
    "Un phénomène de la tectonique des plaques",
    "Un organite cellulaire",
    "Un phénomène d'optique",
    "Un gaz à effet de serre",
    "Une loi de la physique",
    "Un mathématicien célèbre",
    "Un algorithme connu",
    "Un type d'onde électromagnétique",
    "Un acide aminé essentiel",
    "Un champignon ou microorganisme étudié",
  ],
};

module.exports = classementQuestions;
