const classementQuestions = {

  manga: [
    { question: "Une waifu", echelle: "de la pire mégère à la meilleure femme" },
    { question: "Un méchant", echelle: "du plus faible au plus fort" },
    { question: "Un personnage de Dragon Ball", echelle: "du moins stylé au plus stylé" },
    { question: "Un héros", echelle: "du plus inutile au plus indispensable" },
    { question: "Une technique de combat", echelle: "de la plus nulle à la plus destructrice" },
    { question: "Un arc narratif", echelle: "du plus ennuyeux au plus épique" },
    { question: "Un personnage de Naruto", echelle: "du plus agaçant au plus badass" },
    { question: "Un personnage surpuissant", echelle: "du moins impressionnant au plus inarrêtable" },
    { question: "Une transformation", echelle: "de la plus décevante à la plus légendaire" },
    { question: "Un duo iconique", echelle: "du moins complémentaire au plus parfait" },
    { question: "Un sensei", echelle: "du plus incompétent au plus légendaire" },
    { question: "Une rivalité", echelle: "de la plus nulle à la plus intense" },
    { question: "Un personnage tragique", echelle: "du moins touchant au plus bouleversant" },
    { question: "Un comic relief", echelle: "du moins drôle au plus hilarant" },
    { question: "Un antagoniste", echelle: "du plus pathétique au plus charismatique" },
    { question: "Un personnage de One Piece", echelle: "du moins puissant au plus puissant" },
    { question: "Un pouvoir absurde", echelle: "du plus inutile au plus broken" },
    { question: "Un opening de manga", echelle: "du plus oubliable au plus culte" },
    { question: "Un personnage mystérieux", echelle: "du plus transparent au plus insondable" },
    { question: "Un betrayal", echelle: "du moins choquant au plus dévastateur" },
    { question: "Un power-up", echelle: "du plus décevant au plus satisfaisant" },
    { question: "Un personnage de Bleach", echelle: "du moins impressionnant au plus iconique" },
    { question: "Un combat de manga", echelle: "du plus banal au plus légendaire" },
    { question: "Une romance de manga", echelle: "de la plus frustrante à la plus belle" },
    { question: "Un personnage intelligent", echelle: "du moins malin au plus génie" },
    { question: "Un personnage de My Hero Academia", echelle: "du plus inutile au plus overpowered" },
    { question: "Un monde de manga", echelle: "du moins immersif au plus fascinant" },
    { question: "Une arme signature", echelle: "de la plus basique à la plus iconique" },
    { question: "Un personnage de Demon Slayer", echelle: "du moins charismatique au plus stylé" },
    { question: "Un final de manga", echelle: "du plus décevant au plus satisfaisant" },
    { question: "Un protagoniste", echelle: "du plus agaçant au plus attachant" },
    { question: "Un side character", echelle: "du plus oublié au plus mérité d'un spin-off" },
    { question: "Un personnage de Death Note", echelle: "du moins intelligent au plus génie" },
    { question: "Un husbando", echelle: "du moins séduisant au plus parfait" },
    { question: "Un personnage de Jujutsu Kaisen", echelle: "du plus faible au plus terrifiant" },
    { question: "Un design de personnage", echelle: "du plus générique au plus iconique" },
    { question: "Un manga shonen", echelle: "du moins incontournable au plus culte" },
    { question: "Un personnage de Hunter x Hunter", echelle: "du moins mémorable au plus légendaire" },
    { question: "Une mort de personnage", echelle: "de la plus insignifiante à la plus marquante" },
    { question: "Un filler de manga", echelle: "du plus insupportable au plus acceptable" },
  ],

  cinema: [
    { question: "Un film de science-fiction", echelle: "du plus oubliable au plus culte" },
    { question: "Un méchant de film", echelle: "du plus pathétique au plus terrifiant" },
    { question: "Un héros d'action", echelle: "du moins badass au plus légendaire" },
    { question: "Un film qui fait pleurer", echelle: "du moins émouvant au plus dévastateur" },
    { question: "Un film d'horreur", echelle: "du moins flippant au plus traumatisant" },
    { question: "Un réalisateur", echelle: "du moins talentueux au plus génial" },
    { question: "Un film d'animation", echelle: "du moins magique au plus chef-d'œuvre" },
    { question: "Un acteur hollywoodien", echelle: "du moins charismatique au plus iconique" },
    { question: "Un film surestimé", echelle: "du moins surestimé au plus incompréhensible" },
    { question: "Un film sous-estimé", echelle: "du moins méconnu au plus injustement ignoré" },
    { question: "Un film des années 80", echelle: "du plus vieilli au plus intemporel" },
    { question: "Un twist de fin", echelle: "du plus prévisible au plus dévastateur" },
    { question: "Un personnage secondaire", echelle: "du moins attachant au plus voleur de scène" },
    { question: "Un film de super-héros", echelle: "du plus générique au plus exceptionnel" },
    { question: "Un film romantique", echelle: "du plus cliché au plus touchant" },
    { question: "Un film policier", echelle: "du moins captivant au plus haletant" },
    { question: "Un acteur qui joue toujours le même rôle", echelle: "du moins agaçant au plus attachant" },
    { question: "Un film culte des années 90", echelle: "du moins incontournable au plus légendaire" },
    { question: "Un remake", echelle: "du plus raté au plus réussi" },
    { question: "Un film de gangsters", echelle: "du moins intense au plus épique" },
    { question: "Un film d'espionnage", echelle: "du plus convenu au plus haletant" },
    { question: "Un personnage de film qu'on aurait voulu être", echelle: "du moins enviable au plus dream" },
    { question: "Un film qu'on a vu 10 fois", echelle: "du moins mémorable au plus parfait" },
    { question: "Un flop au box-office", echelle: "du plus mérité au plus injuste" },
    { question: "Un film français", echelle: "du moins mémorable au plus incontournable" },
    { question: "Un film japonais", echelle: "du plus hermétique au plus universel" },
    { question: "Une bande originale de film", echelle: "de la plus oubliable à la plus iconique" },
    { question: "Un casting parfait", echelle: "du moins évident au plus génial" },
    { question: "Un film avec un budget monstre", echelle: "du plus gâché au plus spectaculaire" },
    { question: "Un documentaire", echelle: "du moins marquant au plus bouleversant" },
    { question: "Un biopic", echelle: "du moins fidèle au plus inspirant" },
    { question: "Un film d'animation japonais", echelle: "du moins accessible au plus chef-d'œuvre" },
    { question: "Un film avec une fin ouverte", echelle: "de la plus frustrante à la plus parfaite" },
    { question: "Une actrice", echelle: "de la moins marquante à la plus légendaire" },
    { question: "Un film de zombies", echelle: "du plus banal au plus original" },
    { question: "Un film avec un enfant comme héros", echelle: "du plus agaçant au plus touchant" },
    { question: "Un film de guerre", echelle: "du moins réaliste au plus marquant" },
    { question: "Un film de Noël", echelle: "du plus insupportable au plus incontournable" },
    { question: "Un crossover cinématographique", echelle: "du plus décevant au plus jouissif" },
    { question: "Un film d'aventure", echelle: "du moins dépaysant au plus épique" },
  ],

  geographie: [
    { question: "Une destination de rêve", echelle: "de la moins attrayante à la plus paradisiaque" },
    { question: "Un pays où tu ne veux pas vivre", echelle: "du plus vivable au plus invivable" },
    { question: "Un monument iconique", echelle: "du moins impressionnant au plus époustouflant" },
    { question: "Une plage", echelle: "de la plus banale à la plus paradisiaque" },
    { question: "Un pays avec la meilleure cuisine", echelle: "du moins savoureux au plus exceptionnel" },
    { question: "Un pays dangereux", echelle: "du moins risqué au plus extrême" },
    { question: "Un paysage naturel", echelle: "du moins spectaculaire au plus époustouflant" },
    { question: "Un pays sous-estimé", echelle: "du plus connu au plus méconnu injustement" },
    { question: "Une capitale", echelle: "de la moins dynamique à la plus incontournable" },
    { question: "Un pays avec le meilleur niveau de vie", echelle: "du moins confortable au plus idéal" },
    { question: "Une montagne", echelle: "de la moins impressionnante à la plus légendaire" },
    { question: "Un désert", echelle: "du moins hostile au plus inhospitalier" },
    { question: "Une île", echelle: "de la moins isolée à la plus paradisiaque" },
    { question: "Un pays avec la langue la plus difficile", echelle: "de la plus accessible à la plus impossible" },
    { question: "Un pays avec les habitants les plus sympas", echelle: "des moins accueillants aux plus chaleureux" },
    { question: "Une ville la plus festive", echelle: "de la plus calme à la plus folle" },
    { question: "Un pays avec l'histoire la plus riche", echelle: "du moins fascinant au plus incroyable" },
    { question: "Un fleuve célèbre", echelle: "du moins impressionnant au plus mythique" },
    { question: "Un pays avec le foot le plus passionné", echelle: "du moins enflammé au plus extrême" },
    { question: "Un pays à visiter avant de mourir", echelle: "du moins urgent au plus incontournable" },
    { question: "Un pays avec le drapeau le plus beau", echelle: "du plus banal au plus magnifique" },
    { question: "Un pays enclavé", echelle: "du moins isolé au plus méconnu" },
    { question: "Une ville la plus chère", echelle: "de la moins onéreuse à la plus ruineuse" },
    { question: "Un pays avec la nature la plus incroyable", echelle: "du moins sauvage au plus fascinant" },
    { question: "Un pays où on mange dans la rue", echelle: "du moins savoureux au plus incroyable" },
    { question: "Un archipel", echelle: "du moins paradisiaque au plus idyllique" },
    { question: "Un pays froid", echelle: "du moins glacial au plus sibérien" },
    { question: "Une ville fantôme", echelle: "de la moins mystérieuse à la plus fascinante" },
    { question: "Un pays avec le sport national le plus bizarre", echelle: "du plus banal au plus improbable" },
    { question: "Un pays qui n'existe plus", echelle: "du moins marquant au plus fascinant historiquement" },
    { question: "Un pays avec la meilleure musique", echelle: "du moins rythmé au plus envoûtant" },
    { question: "Un pays avec les plus beaux couchers de soleil", echelle: "du moins spectaculaire au plus magique" },
    { question: "Un pays avec la faune la plus incroyable", echelle: "du moins exotique au plus fascinant" },
    { question: "Une ville la plus belle architecturalement", echelle: "de la moins inspirante à la plus magnifique" },
    { question: "Un pays avec le meilleur café", echelle: "du moins bon au plus exceptionnel" },
    { question: "Un pays avec les meilleures fêtes traditionnelles", echelle: "des moins spectaculaires aux plus incroyables" },
    { question: "Un pays avec les routes les plus dangereuses", echelle: "des moins risquées aux plus terrifiantes" },
    { question: "Un pays avec le meilleur vin", echelle: "du moins raffiné au plus divin" },
    { question: "Une ville la plus romantique", echelle: "de la moins romantique à la plus envoûtante" },
    { question: "Un pays avec les meilleures plages de surf", echelle: "des moins mythiques aux plus légendaires" },
  ],

  personnalites: [
    { question: "Un génie scientifique", echelle: "du moins brillant au plus révolutionnaire" },
    { question: "Un dictateur", echelle: "du moins cruel au plus tyrannique" },
    { question: "Un artiste révolutionnaire", echelle: "du moins avant-gardiste au plus visionnaire" },
    { question: "Un leader charismatique", echelle: "du moins inspirant au plus légendaire" },
    { question: "Un entrepreneur", echelle: "du moins visionnaire au plus révolutionnaire" },
    { question: "Un philosophe", echelle: "du moins accessible au plus influent" },
    { question: "Un sportif légendaire", echelle: "du moins impressionnant au plus inarrêtable" },
    { question: "Un personnage historique controversé", echelle: "du moins clivant au plus polarisant" },
    { question: "Un révolutionnaire", echelle: "du moins radical au plus marquant" },
    { question: "Un explorateur", echelle: "du moins aventurier au plus intrépide" },
    { question: "Une femme qui a changé l'histoire", echelle: "de la moins connue à la plus influente" },
    { question: "Un inventeur", echelle: "du moins impactant au plus révolutionnaire" },
    { question: "Un écrivain", echelle: "du moins accessible au plus incontournable" },
    { question: "Un peintre", echelle: "du moins connu au plus iconique" },
    { question: "Un président", echelle: "du moins marquant au plus légendaire" },
    { question: "Un roi ou reine", echelle: "du moins mémorable au plus légendaire" },
    { question: "Un criminel notoire", echelle: "du moins dangereux au plus terrifiant" },
    { question: "Un activiste", echelle: "du moins influent au plus marquant" },
    { question: "Un personnage historique courageux", echelle: "du moins audacieux au plus héroïque" },
    { question: "Un personnage mort trop tôt", echelle: "du moins regretté au plus cruellement disparu" },
    { question: "Un traître célèbre", echelle: "du moins choquant au plus dévastateur" },
    { question: "Un héros de guerre", echelle: "du moins courageux au plus légendaire" },
    { question: "Un artiste maudit", echelle: "du moins torturé au plus tragique" },
    { question: "Un personnage le plus influent", echelle: "du moins impactant au plus déterminant" },
    { question: "Un musicien classique", echelle: "du moins accessible au plus génial" },
    { question: "Un conquérant", echelle: "du moins ambitieux au plus dévastateur" },
    { question: "Un personnage avec le plus grand ego", echelle: "du plus modeste au plus mégalomane" },
    { question: "Un espion célèbre", echelle: "du moins efficace au plus légendaire" },
    { question: "Un philanthrope", echelle: "du moins généreux au plus altruiste" },
    { question: "Un personnage injustement oublié", echelle: "du moins méconnu au plus sous-estimé par l'histoire" },
    { question: "Un génie incompris", echelle: "du moins marginalisé au plus en avance sur son temps" },
    { question: "Un prix Nobel", echelle: "du moins marquant au plus révolutionnaire" },
    { question: "Un personnage dont on parle encore dans 500 ans", echelle: "du moins intemporel au plus immortel" },
    { question: "Un mythe vivant", echelle: "du moins légendaire au plus immortel" },
    { question: "Un personnage le plus charismatique", echelle: "du moins magnétique au plus hypnotique" },
    { question: "Un stratège militaire", echelle: "du moins brillant au plus génial" },
    { question: "Un réformateur social", echelle: "du moins impactant au plus transformateur" },
    { question: "Un architecte célèbre", echelle: "du moins connu au plus visionnaire" },
    { question: "Un astronaute", echelle: "du moins courageux au plus légendaire" },
    { question: "Un chef cuisinier étoilé", echelle: "du moins talentueux au plus révolutionnaire" },
  ],

  histoire: [
    { question: "Une guerre", echelle: "de la moins dévastatrice à la plus catastrophique" },
    { question: "Une révolution", echelle: "de la moins radicale à la plus bouleversante" },
    { question: "Un empire", echelle: "du moins puissant au plus dévastateur" },
    { question: "Une civilisation disparue", echelle: "de la moins fascinante à la plus mystérieuse" },
    { question: "Une bataille décisive", echelle: "de la moins connue à la plus déterminante" },
    { question: "Une invention historique", echelle: "de la moins impactante à la plus révolutionnaire" },
    { question: "Un génocide", echelle: "du moins connu au plus tragique historiquement" },
    { question: "Une période sombre", echelle: "de la moins terrible à la plus cauchemardesque" },
    { question: "Une période dorée", echelle: "de la moins prospère à la plus extraordinaire" },
    { question: "Un événement qu'on aurait voulu éviter", echelle: "du moins tragique au plus dévastateur" },
    { question: "Un accord de paix", echelle: "du moins impactant au plus historique" },
    { question: "Un coup d'état", echelle: "du moins choquant au plus dévastateur" },
    { question: "Un mouvement social", echelle: "du moins influent au plus révolutionnaire" },
    { question: "Une découverte géographique", echelle: "de la moins marquante à la plus déterminante" },
    { question: "Un complot historique", echelle: "du moins audacieux au plus dévastateur" },
    { question: "Une épidémie historique", echelle: "de la moins connue à la plus dévastatrice" },
    { question: "Un mouvement de libération", echelle: "du moins connu au plus inspirant" },
    { question: "Un attentat historique", echelle: "du moins connu au plus marquant" },
    { question: "Une trahison historique", echelle: "de la moins choquante à la plus dévastatrice" },
    { question: "Un héros oublié", echelle: "du moins méconnu au plus injustement ignoré" },
    { question: "Une erreur historique monumentale", echelle: "de la moins grave à la plus catastrophique" },
    { question: "Un miracle historique", echelle: "du moins improbable au plus incroyable" },
    { question: "Un traité historique", echelle: "du moins impactant au plus déterminant" },
    { question: "Une colonisation", echelle: "de la moins dévastatrice à la plus brutale" },
    { question: "Une résistance", echelle: "de la moins courageuse à la plus héroïque" },
    { question: "Un procès célèbre", echelle: "du moins retentissant au plus marquant" },
    { question: "Un mouvement artistique historique", echelle: "du moins connu au plus influent" },
    { question: "Un exil célèbre", echelle: "du moins dramatique au plus tragique" },
    { question: "Une propagande célèbre", echelle: "de la moins efficace à la plus dévastatrice" },
    { question: "Un monument construit par la force", echelle: "du moins connu au plus tristement célèbre" },
    { question: "Un naufrage célèbre", echelle: "du moins connu au plus tragique" },
    { question: "Une exploration spatiale", echelle: "de la moins marquante à la plus historique" },
    { question: "Un mur ou frontière historique", echelle: "du moins symbolique au plus tristement célèbre" },
    { question: "Une famine historique", echelle: "de la moins connue à la plus dévastatrice" },
    { question: "Un empire colonial", echelle: "du moins brutal au plus dévastateur" },
    { question: "Une déclaration d'indépendance", echelle: "de la moins connue à la plus historique" },
    { question: "Un armistice célèbre", echelle: "du moins connu au plus historique" },
    { question: "Une période d'occupation", echelle: "de la moins brutale à la plus oppressive" },
    { question: "Un blocus historique", echelle: "du moins impactant au plus dévastateur" },
    { question: "Une révolution industrielle", echelle: "de la moins transformatrice à la plus déterminante" },
  ],

  jeuxvideo: [
    { question: "Un boss final", echelle: "du plus facile au plus cauchemardesque" },
    { question: "Un personnage jouable", echelle: "du moins fun au plus iconique" },
    { question: "Un jeu impossible à finir", echelle: "du moins difficile au plus sadique" },
    { question: "Un monde ouvert", echelle: "du moins immersif au plus incroyable" },
    { question: "Un jeu multijoueur", echelle: "du moins addictif au plus chronophage" },
    { question: "Un jeu de sport", echelle: "du moins réaliste au plus incontournable" },
    { question: "Un RPG", echelle: "du moins épique au plus révolutionnaire" },
    { question: "Un jeu indé", echelle: "du moins méconnu au plus chef-d'œuvre" },
    { question: "Un jeu surestimé", echelle: "du moins surestimé au plus incompréhensible" },
    { question: "Un antagoniste de jeu", echelle: "du plus pathétique au plus terrifiant" },
    { question: "Une musique de jeu", echelle: "de la plus oubliable à la plus culte" },
    { question: "Un jeu avec un scénario incroyable", echelle: "du moins prenant au plus bouleversant" },
    { question: "Un jeu d'enfance", echelle: "du moins nostalgique au plus déterminant" },
    { question: "Un glitch mémorable", echelle: "du moins drôle au plus légendaire" },
    { question: "Un jeu qu'on joue encore aujourd'hui", echelle: "du moins intemporel au plus culte" },
    { question: "Un DLC", echelle: "du plus arnaque au plus indispensable" },
    { question: "Un jeu qui a créé un genre", echelle: "du moins influent au plus révolutionnaire" },
    { question: "Un reboot de jeu", echelle: "du plus raté au plus réussi" },
    { question: "Un jeu avec le meilleur lore", echelle: "du moins profond au plus fascinant" },
    { question: "Un personnage féminin de jeu", echelle: "de la moins mémorable à la plus iconique" },
    { question: "Un jeu qu'on regrette d'avoir acheté", echelle: "du moins décevant au plus arnaque totale" },
    { question: "Un jeu qui nous a fait ressentir quelque chose", echelle: "du moins émouvant au plus dévastateur" },
    { question: "Un easter egg de jeu", echelle: "du moins cool au plus légendaire" },
    { question: "Un jeu de baston", echelle: "du moins équilibré au plus parfait" },
    { question: "Un jeu de plateforme", echelle: "du moins mémorable au plus culte" },
    { question: "Un jeu d'horreur", echelle: "du moins flippant au plus traumatisant" },
    { question: "Un jeu de stratégie", echelle: "du moins complexe au plus addictif" },
    { question: "Un niveau de jeu", echelle: "du moins mémorable au plus légendaire" },
    { question: "Un jeu avec la meilleure communauté", echelle: "de la plus toxique à la plus soudée" },
    { question: "Un jeu avec le plus de heures de jeu", echelle: "du moins chronophage au plus dévorant" },
    { question: "Un console mythique", echelle: "de la moins incontournable à la plus révolutionnaire" },
    { question: "Un jeu de course", echelle: "du moins fun au plus addictif" },
    { question: "Un jeu de tir", echelle: "du moins mémorable au plus incontournable" },
    { question: "Un personnage qu'on joue en premier", echelle: "du moins évident au plus parfait" },
    { question: "Un jeu qu'on offrirait à tout le monde", echelle: "du moins universel au plus indispensable" },
    { question: "Un speedrun impressionnant", echelle: "du moins incroyable au plus hallucinant" },
    { question: "Un jeu avec le meilleur système de combat", echelle: "du moins satisfaisant au plus parfait" },
    { question: "Un jeu abandonné", echelle: "du moins dommage au plus tragique" },
    { question: "Un crossover de jeux", echelle: "du plus improbable au plus jouissif" },
    { question: "Un jeu graphiquement en avance sur son temps", echelle: "du moins impressionnant au plus révolutionnaire" },
  ],

  gastronomie: [
    { question: "Un plat réconfortant", echelle: "du moins réconfortant au plus câlin pour l'âme" },
    { question: "Un plat de fête", echelle: "du moins festif au plus exceptionnel" },
    { question: "Un dessert", echelle: "du moins gourmand au plus irrésistible" },
    { question: "Un fromage", echelle: "du moins fort au plus puissant" },
    { question: "Un cocktail", echelle: "du moins festif au plus parfait" },
    { question: "Un plat de rue", echelle: "du moins savoureux au plus incroyable" },
    { question: "Un plat qu'on déteste mais tout le monde adore", echelle: "du plus compréhensible au plus mystérieux" },
    { question: "Un fast food", echelle: "du moins savoureux au plus addictif" },
    { question: "Un snack addictif", echelle: "du moins dangereux au plus incontrôlable" },
    { question: "Un plat épicé", echelle: "du moins relevé au plus volcanique" },
    { question: "Un plat trop calorique", echelle: "du moins coupable au plus péché mortel" },
    { question: "Un plat qu'on mange à 3h du matin", echelle: "du moins honteux au plus assumé" },
    { question: "Un accord mets-vins", echelle: "du moins évident au plus parfait" },
    { question: "Un plat de grand-mère", echelle: "du moins nostalgique au plus irremplaçable" },
    { question: "Un fruit exotique", echelle: "du moins accessible au plus dépaysant" },
    { question: "Un condiment", echelle: "du moins indispensable au plus révolutionnaire" },
    { question: "Un plat végétarien", echelle: "du moins convainquant au plus délicieux" },
    { question: "Un plat sucré-salé", echelle: "du plus déstabilisant au plus parfait" },
    { question: "Un plat qu'on commande toujours au restau", echelle: "du moins incontournable au plus réflexe" },
    { question: "Un plat impressionnant en soirée", echelle: "du moins impressionnant au plus show-off" },
    { question: "Un plat qu'on ne sait pas prononcer", echelle: "du plus prononçable au plus imprononcable" },
    { question: "Un ingrédient qu'on met partout", echelle: "du moins universel au plus indispensable" },
    { question: "Un plat de la mer", echelle: "du moins frais au plus exceptionnel" },
    { question: "Un plat carnivore", echelle: "du moins intense au plus bestial" },
    { question: "Un plat qu'on mange avec les doigts", echelle: "du moins convivial au plus festif" },
    { question: "Une cuisine du monde", echelle: "de la moins connue à la plus incontournable" },
    { question: "Un petit-déjeuner idéal", echelle: "du moins énergisant au plus parfait" },
    { question: "Un plat du dimanche", echelle: "du moins familial au plus sacré" },
    { question: "Un légume sous-estimé", echelle: "du moins ignoré au plus injustement oublié" },
    { question: "Une boisson chaude", echelle: "de la moins réconfortante à la plus parfaite" },
    { question: "Un plat qu'on mangerait tous les jours", echelle: "du moins évident au plus addictif" },
    { question: "Un restaurant étoilé", echelle: "du moins accessible au plus mythique" },
    { question: "Un plat du monde découvert en voyage", echelle: "du moins révélateur au plus bouleversant" },
    { question: "Un plat fermenté", echelle: "du moins audacieux au plus acquis" },
    { question: "Un pain", echelle: "du moins mémorable au plus incontournable" },
    { question: "Une sauce", echelle: "de la moins indispensable à la plus révolutionnaire" },
    { question: "Un plat typiquement français", echelle: "du moins connu au plus incontournable" },
    { question: "Un plat asiatique", echelle: "du moins dépaysant au plus addictif" },
    { question: "Un aliment qu'on aime en secret", echelle: "du moins honteux au plus totalement assumé" },
    { question: "Un plat avec le meilleur rapport qualité-prix", echelle: "du moins avantageux au plus parfait" },
  ],

  musique: [
    { question: "Un artiste intemporel", echelle: "du moins éternel au plus légendaire" },
    { question: "Un album culte", echelle: "du moins marquant au plus chef-d'œuvre absolu" },
    { question: "Une chanson pour se motiver", echelle: "de la moins efficace à la plus électrisante" },
    { question: "Une chanson pour pleurer", echelle: "de la moins émouvante à la plus dévastatrice" },
    { question: "Un genre musical", echelle: "du moins influent au plus révolutionnaire" },
    { question: "Un festival", echelle: "du moins incontournable au plus légendaire" },
    { question: "Un instrument de musique", echelle: "du moins reconnaissable au plus iconique" },
    { question: "Un one-hit wonder", echelle: "du moins mémorable au plus injustement limité" },
    { question: "Un artiste qui aurait dû s'arrêter avant", echelle: "du moins regrettable au plus dommage" },
    { question: "Un comeback d'artiste", echelle: "du plus décevant au plus réussi" },
    { question: "Un clip iconique", echelle: "du moins mémorable au plus légendaire" },
    { question: "Un refrain qui reste en tête", echelle: "du moins entêtant au plus impossible à oublier" },
    { question: "Un artiste des années 80", echelle: "du moins intemporel au plus culte" },
    { question: "Un artiste des années 90", echelle: "du moins nostalgique au plus légendaire" },
    { question: "Un rappeur français", echelle: "du moins influent au plus incontournable" },
    { question: "Un groupe de rock", echelle: "du moins légendaire au plus révolutionnaire" },
    { question: "Une bande originale de film", echelle: "de la plus oubliable à la plus iconique" },
    { question: "Un DJ", echelle: "du moins connu au plus légendaire" },
    { question: "Un artiste mort trop tôt", echelle: "du moins regretté au plus cruellement disparu" },
    { question: "Un beatmaker", echelle: "du moins reconnu au plus révolutionnaire" },
    { question: "Une voix unique", echelle: "de la moins reconnaissable à la plus inimitable" },
    { question: "Un artiste avec le meilleur style", echelle: "du moins iconique au plus légendaire" },
    { question: "Une tournée légendaire", echelle: "de la moins mémorable à la plus historique" },
    { question: "Un label mythique", echelle: "du moins influent au plus déterminant" },
    { question: "Une chanson interdite à la radio", echelle: "de la moins choquante à la plus controversée" },
    { question: "Un artiste overrated", echelle: "du moins surestimé au plus incompréhensible" },
    { question: "Un artiste underrated", echelle: "du moins méconnu au plus injustement ignoré" },
    { question: "Une collab musicale", echelle: "de la plus improbable à la plus géniale" },
    { question: "Un son qui définit une génération", echelle: "du moins représentatif au plus emblématique" },
    { question: "Une chanson de rupture", echelle: "de la moins poignante à la plus dévastatrice" },
    { question: "Un artiste actuel", echelle: "du moins prometteur au plus incontournable" },
    { question: "Une intro reconnaissable", echelle: "de la moins évidente à la plus iconique" },
    { question: "Un concert mythique", echelle: "du moins légendaire au plus historique" },
    { question: "Un artiste polyvalent", echelle: "du moins versatile au plus touche-à-tout" },
    { question: "Une chanson de fête", echelle: "de la moins festive à la plus inévitable" },
    { question: "Un tube de l'été", echelle: "du moins mémorable au plus indestructible" },
    { question: "Un artiste avec la plus longue carrière", echelle: "du moins durable au plus intemporel" },
    { question: "Un morceau de jazz", echelle: "du moins accessible au plus sublissime" },
    { question: "Une chanson engagée", echelle: "de la moins percutante à la plus marquante" },
    { question: "Un opéra célèbre", echelle: "du moins accessible au plus incontournable" },
  ],

  sport: [
    { question: "Un sportif légendaire", echelle: "du moins impressionnant au plus inarrêtable" },
    { question: "Un sport qu'on pratique", echelle: "du moins exigeant au plus addictif" },
    { question: "Un sport qu'on ne comprend pas", echelle: "du moins mystérieux au plus incompréhensible" },
    { question: "Un match historique", echelle: "du moins mémorable au plus légendaire" },
    { question: "Un stade iconique", echelle: "du moins impressionnant au plus mythique" },
    { question: "Un transfert choquant", echelle: "du moins surprenant au plus incompréhensible" },
    { question: "Un scandale sportif", echelle: "du moins choquant au plus dévastateur" },
    { question: "Un record sportif", echelle: "du moins impressionnant au plus inarrêtable" },
    { question: "Une rivalité sportive", echelle: "de la moins intense à la plus épique" },
    { question: "Un sport extrême", echelle: "du moins dangereux au plus suicidaire" },
    { question: "Un sport olympique", echelle: "du moins spectaculaire au plus grisant" },
    { question: "Un entraîneur légendaire", echelle: "du moins inspirant au plus légendaire" },
    { question: "Un sport de combat", echelle: "du moins violent au plus brutal" },
    { question: "Un sport d'hiver", echelle: "du moins accessible au plus extrême" },
    { question: "Un sport avec les règles les plus bizarres", echelle: "des moins étranges aux plus incompréhensibles" },
    { question: "Un moment de fair-play", echelle: "du moins touchant au plus exemplaire" },
    { question: "Un moment de triche célèbre", echelle: "du moins choquant au plus scandaleux" },
    { question: "Un come-back sportif", echelle: "du moins incroyable au plus miraculeux" },
    { question: "Une défaite historique", echelle: "de la moins douloureuse à la plus catastrophique" },
    { question: "Un sport qui devrait être aux JO", echelle: "du moins légitime au plus évident" },
    { question: "Un palmarès de sportif", echelle: "du moins impressionnant au plus inarrêtable" },
    { question: "Un club de football", echelle: "du moins historique au plus légendaire" },
    { question: "Un sport nautique", echelle: "du moins accessible au plus extrême" },
    { question: "Un sport motorisé", echelle: "du moins rapide au plus adrénaline" },
    { question: "Un sportif reconverti", echelle: "du moins réussi au plus surprenant" },
    { question: "Un sport qu'on aimerait pratiquer", echelle: "du moins accessible au plus dream" },
    { question: "Un arbitre controversé", echelle: "du moins contesté au plus détesté" },
    { question: "Un sport de raquette", echelle: "du moins exigeant au plus noble" },
    { question: "Un supporter emblématique", echelle: "du moins passionné au plus légendaire" },
    { question: "Un sport individuel", echelle: "du moins solitaire au plus mental" },
    { question: "Un sport d'équipe", echelle: "du moins collectif au plus soudé" },
    { question: "Un dribble ou geste technique célèbre", echelle: "du moins impressionnant au plus magique" },
    { question: "Une compétition annuelle", echelle: "de la moins incontournable à la plus légendaire" },
    { question: "Un sport sous-estimé", echelle: "du moins méconnu au plus injustement ignoré" },
    { question: "Un athlète polyvalent", echelle: "du moins versatile au plus exceptionnel" },
    { question: "Un sport inventé récemment", echelle: "du moins sérieux au plus prometteur" },
    { question: "Une victoire impossible", echelle: "de la moins incroyable à la plus miraculeuse" },
    { question: "Un sport de montagne", echelle: "du moins risqué au plus extrême" },
    { question: "Un sport américain", echelle: "du moins compréhensible au plus captivant" },
    { question: "Un sport avec le meilleur ambiance", echelle: "du moins festif au plus électrique" },
  ],

  science: [
    { question: "Une découverte scientifique", echelle: "de la moins révolutionnaire à la plus déterminante" },
    { question: "Un animal étrange", echelle: "du moins bizarre au plus improbable" },
    { question: "Un phénomène naturel", echelle: "du moins impressionnant au plus dévastateur" },
    { question: "Une planète", echelle: "de la moins fascinante à la plus mystérieuse" },
    { question: "Un élément chimique", echelle: "du moins dangereux au plus mortel" },
    { question: "Une invention du XXe siècle", echelle: "de la moins impactante à la plus révolutionnaire" },
    { question: "Une maladie mystérieuse", echelle: "de la moins inquiétante à la plus terrifiante" },
    { question: "Un animal disparu", echelle: "du moins regretté au plus cruellement absent" },
    { question: "Un animal qu'on ne veut pas croiser", echelle: "du moins dangereux au plus terrifyant" },
    { question: "Un phénomène météo extrême", echelle: "du moins dévastateur au plus cataclysmique" },
    { question: "Un paradoxe scientifique", echelle: "du moins déroutant au plus impossible à comprendre" },
    { question: "Un mystère de l'univers", echelle: "du moins intriguant au plus insondable" },
    { question: "Un robot ou IA", echelle: "du moins impressionnant au plus révolutionnaire" },
    { question: "Un virus célèbre", echelle: "du moins dangereux au plus dévastateur" },
    { question: "Un vaccin", echelle: "du moins impactant au plus révolutionnaire" },
    { question: "Un record scientifique", echelle: "du moins impressionnant au plus hallucinant" },
    { question: "Un super-pouvoir animal", echelle: "du moins impressionnant au plus incroyable" },
    { question: "Un organe humain", echelle: "du moins indispensable au plus vital" },
    { question: "Un phénomène quantique", echelle: "du moins déroutant au plus incompréhensible" },
    { question: "Une énergie du futur", echelle: "de la moins prometteuse à la plus révolutionnaire" },
    { question: "Un poison naturel", echelle: "du moins dangereux au plus mortel" },
    { question: "Une symbiose animale", echelle: "de la moins fascinante à la plus incroyable" },
    { question: "Un écosystème unique", echelle: "du moins fragile au plus irremplaçable" },
    { question: "Une espèce invasive", echelle: "de la moins problématique à la plus dévastatrice" },
    { question: "Un phénomène lumineux naturel", echelle: "du moins spectaculaire au plus magique" },
    { question: "Un scientifique génial", echelle: "du moins connu au plus révolutionnaire" },
    { question: "Un trou noir", echelle: "du moins impressionnant au plus terrifiant" },
    { question: "Un matériau incroyable", echelle: "du moins étonnant au plus révolutionnaire" },
    { question: "Un aliment aux super-propriétés", echelle: "du moins connu au plus miraculeux" },
    { question: "Une théorie scientifique", echelle: "de la moins accessible à la plus révolutionnaire" },
    { question: "Un satellite ou sonde spatiale", echelle: "du moins marquant au plus historique" },
    { question: "Un sens qu'on aimerait avoir", echelle: "du moins utile au plus fascinant" },
    { question: "Une catastrophe naturelle", echelle: "de la moins dévastatrice à la plus cataclysmique" },
    { question: "Un insecte fascinant", echelle: "du moins connu au plus extraordinaire" },
    { question: "Un fossile célèbre", echelle: "du moins connu au plus révolutionnaire" },
    { question: "Un phénomène céleste", echelle: "du moins spectaculaire au plus magique" },
    { question: "Un clone ou créature génétiquement modifiée", echelle: "du moins révolutionnaire au plus controversé" },
    { question: "Un biome", echelle: "du moins fascinant au plus incroyable" },
    { question: "Un remède miracle", echelle: "du moins efficace au plus révolutionnaire" },
    { question: "Une mutation génétique connue", echelle: "de la moins impressionnante à la plus fascinante" },
  ],

};

module.exports = classementQuestions;
