module.exports = [
  // ── Shōnen ──────────────────────────────────────────────────────────
  { character: "Naruto Uzumaki", manga: "Naruto", category: "shonen", aliases: ["naruto"] },
  { character: "Sasuke Uchiha", manga: "Naruto", category: "shonen", aliases: ["sasuke"] },
  { character: "Kakashi Hatake", manga: "Naruto", category: "shonen", aliases: ["kakashi"] },
  { character: "Rock Lee", manga: "Naruto", category: "shonen", aliases: ["lee"] },
  { character: "Itachi Uchiha", manga: "Naruto", category: "shonen", aliases: ["itachi"] },
  { character: "Monkey D. Luffy", manga: "One Piece", category: "shonen", aliases: ["luffy"] },
  { character: "Roronoa Zoro", manga: "One Piece", category: "shonen", aliases: ["zoro"] },
  { character: "Sanji", manga: "One Piece", category: "shonen", aliases: ["sanji"] },
  { character: "Portgas D. Ace", manga: "One Piece", category: "shonen", aliases: ["ace"] },
  { character: "Nico Robin", manga: "One Piece", category: "shonen", aliases: ["robin"] },
  { character: "Son Goku", manga: "Dragon Ball", category: "shonen", aliases: ["goku", "sangoku"] },
  { character: "Vegeta", manga: "Dragon Ball", category: "shonen", aliases: ["vegeta"] },
  { character: "Gohan", manga: "Dragon Ball", category: "shonen", aliases: ["gohan"] },
  { character: "Piccolo", manga: "Dragon Ball", category: "shonen", aliases: ["piccolo"] },
  { character: "Eren Yeager", manga: "L'Attaque des Titans", category: "shonen", aliases: ["eren"] },
  { character: "Levi Ackerman", manga: "L'Attaque des Titans", category: "shonen", aliases: ["levi"] },
  { character: "Armin Arlert", manga: "L'Attaque des Titans", category: "shonen", aliases: ["armin"] },
  { character: "Mikasa Ackerman", manga: "L'Attaque des Titans", category: "shonen", aliases: ["mikasa"] },
  { character: "Izuku Midoriya", manga: "My Hero Academia", category: "shonen", aliases: ["deku", "midoriya", "izuku"] },
  { character: "Katsuki Bakugo", manga: "My Hero Academia", category: "shonen", aliases: ["bakugo", "kacchan"] },
  { character: "All Might", manga: "My Hero Academia", category: "shonen", aliases: ["all might"] },
  { character: "Shoto Todoroki", manga: "My Hero Academia", category: "shonen", aliases: ["todoroki", "shoto"] },
  { character: "Tanjiro Kamado", manga: "Demon Slayer", category: "shonen", aliases: ["tanjiro"] },
  { character: "Zenitsu Agatsuma", manga: "Demon Slayer", category: "shonen", aliases: ["zenitsu"] },
  { character: "Inosuke Hashibira", manga: "Demon Slayer", category: "shonen", aliases: ["inosuke"] },
  { character: "Rengoku Kyojuro", manga: "Demon Slayer", category: "shonen", aliases: ["rengoku"] },
  { character: "Satoru Gojo", manga: "Jujutsu Kaisen", category: "shonen", aliases: ["gojo"] },
  { character: "Yuji Itadori", manga: "Jujutsu Kaisen", category: "shonen", aliases: ["itadori", "yuji"] },
  { character: "Megumi Fushiguro", manga: "Jujutsu Kaisen", category: "shonen", aliases: ["fushiguro", "megumi"] },
  { character: "Nobara Kugisaki", manga: "Jujutsu Kaisen", category: "shonen", aliases: ["nobara"] },
  { character: "Gon Freecss", manga: "Hunter × Hunter", category: "shonen", aliases: ["gon"] },
  { character: "Killua Zoldyck", manga: "Hunter × Hunter", category: "shonen", aliases: ["killua"] },
  { character: "Hisoka", manga: "Hunter × Hunter", category: "shonen", aliases: ["hisoka"] },
  { character: "Edward Elric", manga: "Fullmetal Alchemist", category: "shonen", aliases: ["edward", "ed"] },
  { character: "Roy Mustang", manga: "Fullmetal Alchemist", category: "shonen", aliases: ["mustang", "roy"] },
  { character: "Alphonse Elric", manga: "Fullmetal Alchemist", category: "shonen", aliases: ["alphonse", "al"] },
  { character: "Ichigo Kurosaki", manga: "Bleach", category: "shonen", aliases: ["ichigo"] },
  { character: "Rukia Kuchiki", manga: "Bleach", category: "shonen", aliases: ["rukia"] },
  { character: "Natsu Dragneel", manga: "Fairy Tail", category: "shonen", aliases: ["natsu"] },
  { character: "Erza Scarlet", manga: "Fairy Tail", category: "shonen", aliases: ["erza"] },
  { character: "Asta", manga: "Black Clover", category: "shonen", aliases: ["asta"] },
  { character: "Saitama", manga: "One Punch Man", category: "shonen", aliases: ["saitama"] },
  { character: "Genos", manga: "One Punch Man", category: "shonen", aliases: ["genos"] },
  { character: "Light Yagami", manga: "Death Note", category: "shonen", aliases: ["light", "kira"] },
  { character: "L", manga: "Death Note", category: "shonen", aliases: ["lawliet", "l lawliet"] },
  { character: "Ryuk", manga: "Death Note", category: "shonen", aliases: ["ryuk"] },
  { character: "Hinata Shoyo", manga: "Haikyuu!!", category: "shonen", aliases: ["hinata", "shoyo"] },
  { character: "Tobio Kageyama", manga: "Haikyuu!!", category: "shonen", aliases: ["kageyama"] },
  // ── Shōjo ───────────────────────────────────────────────────────────
  { character: "Usagi Tsukino", manga: "Sailor Moon", category: "shojo", aliases: ["sailor moon", "usagi", "bunny"] },
  { character: "Tohru Honda", manga: "Fruits Basket", category: "shojo", aliases: ["tohru"] },
  { character: "Kyo Sohma", manga: "Fruits Basket", category: "shojo", aliases: ["kyo"] },
  { character: "Haruhi Fujioka", manga: "Ouran Host Club", category: "shojo", aliases: ["haruhi"] },
  { character: "Nana Osaki", manga: "Nana", category: "shojo", aliases: ["nana"] },
  { character: "Sawako Kuronuma", manga: "Kimi ni Todoke", category: "shojo", aliases: ["sawako"] },
  { character: "Yona", manga: "Akatsuki no Yona", category: "shojo", aliases: ["yona"] },
  { character: "Sakura Kinomoto", manga: "Cardcaptor Sakura", category: "shojo", aliases: ["sakura"] },
  { character: "Kyoko Mogami", manga: "Skip Beat", category: "shojo", aliases: ["kyoko"] },
  { character: "Zero Kiryu", manga: "Vampire Knight", category: "shojo", aliases: ["zero"] },
  // ── Seinen ──────────────────────────────────────────────────────────
  { character: "Guts", manga: "Berserk", category: "seinen", aliases: ["guts"] },
  { character: "Griffith", manga: "Berserk", category: "seinen", aliases: ["griffith"] },
  { character: "Kaneki Ken", manga: "Tokyo Ghoul", category: "seinen", aliases: ["kaneki"] },
  { character: "Touka Kirishima", manga: "Tokyo Ghoul", category: "seinen", aliases: ["touka"] },
  { character: "Spike Spiegel", manga: "Cowboy Bebop", category: "seinen", aliases: ["spike"] },
  { character: "Thorfinn", manga: "Vinland Saga", category: "seinen", aliases: ["thorfinn"] },
  { character: "Askeladd", manga: "Vinland Saga", category: "seinen", aliases: ["askeladd"] },
  { character: "Makima", manga: "Chainsaw Man", category: "seinen", aliases: ["makima"] },
  { character: "Denji", manga: "Chainsaw Man", category: "seinen", aliases: ["denji"] },
  { character: "Power", manga: "Chainsaw Man", category: "seinen", aliases: ["power"] },
  { character: "Musashi Miyamoto", manga: "Vagabond", category: "seinen", aliases: ["musashi"] },
];
