module.exports = {
  manga: [
    "Naruto Uzumaki", "Sasuke Uchiha", "Sakura Haruno", "Kakashi Hatake", "Itachi Uchiha",
    "Minato Namikaze", "Hinata Hyuga", "Jiraiya", "Madara Uchiha", "Obito Uchiha",
    "Son Goku", "Vegeta", "Gohan", "Piccolo", "Frieza",
    "Monkey D. Luffy", "Roronoa Zoro", "Sanji", "Shanks", "Trafalgar Law",
    "Ichigo Kurosaki", "Rukia Kuchiki", "Sosuke Aizen",
    "Eren Yeager", "Levi Ackerman", "Mikasa Ackerman", "Armin Arlert",
    "Killua Zoldyck", "Gon Freecss", "Hisoka",
    "Edward Elric", "Roy Mustang",
    "Light Yagami", "L Lawliet",
    "Gojo Satoru", "Yuji Itadori", "Ryomen Sukuna",
    "Tanjiro Kamado", "Zenitsu Agatsuma", "Inosuke Hashibira",
    "Izuku Midoriya", "Katsuki Bakugo", "Shoto Todoroki", "All Might",
    "Spike Spiegel", "Sailor Moon",
  ],
  celebrites: [
    "Elon Musk", "Barack Obama", "Emmanuel Macron", "Donald Trump", "Vladimir Poutine",
    "Beyoncé", "Taylor Swift", "Rihanna", "Lady Gaga", "Adele",
    "Leonardo DiCaprio", "Brad Pitt", "Tom Hanks", "Angelina Jolie",
    "Bill Gates", "Mark Zuckerberg", "Jeff Bezos", "Steve Jobs",
    "Michael Jackson", "Elvis Presley", "Madonna",
    "Eminem", "Drake", "Jay-Z", "Kanye West", "Justin Bieber",
    "Kim Kardashian", "Kylie Jenner", "Shakira", "Celine Dion",
    "Angela Merkel", "Greta Thunberg",
    "Stromae", "Aya Nakamura", "Angèle",
  ],
  cinema: [
    "Harry Potter", "Hermione Granger", "Albus Dumbledore", "Voldemort",
    "Gandalf", "Frodon Sacquet", "Aragorn",
    "Luke Skywalker", "Dark Vador", "Yoda", "Han Solo", "Princesse Leia",
    "Iron Man", "Batman", "Spider-Man", "Captain America", "Thor", "Le Joker",
    "Jack Sparrow", "Indiana Jones", "James Bond",
    "Forrest Gump", "Rocky Balboa", "Tyler Durden", "Don Vito Corleone",
    "Shrek", "Simba", "Woody", "Buzz l'Éclair", "Elsa",
    "Hannibal Lecter", "John Wick", "Tony Montana", "E.T.",
    "Terminator", "Sherlock Holmes", "Dracula",
  ],
  sport: [
    "Kylian Mbappé", "Cristiano Ronaldo", "Lionel Messi", "Neymar Jr", "Zinedine Zidane",
    "Thierry Henry", "Ronaldinho", "Pelé", "Diego Maradona", "Erling Haaland",
    "LeBron James", "Michael Jordan", "Kobe Bryant", "Stephen Curry", "Shaquille O'Neal",
    "Rafael Nadal", "Roger Federer", "Novak Djokovic", "Serena Williams", "Naomi Osaka",
    "Usain Bolt", "Michael Phelps", "Simone Biles", "Teddy Riner",
    "Muhammad Ali", "Mike Tyson", "Floyd Mayweather",
    "Lewis Hamilton", "Max Verstappen", "Ayrton Senna",
    "Tiger Woods", "Tony Hawk", "Lance Armstrong",
  ],
  histoire: [
    "Napoléon Bonaparte", "Jules César", "Alexandre le Grand", "Cléopâtre", "Louis XIV",
    "Jeanne d'Arc", "Charlemagne", "Henri IV", "Marie-Antoinette", "Robespierre",
    "Marie Curie", "Albert Einstein", "Isaac Newton", "Galilée",
    "Léonard de Vinci", "Michel-Ange", "Shakespeare", "Molière",
    "Voltaire", "Karl Marx", "Sigmund Freud", "Charles Darwin",
    "Mahatma Gandhi", "Nelson Mandela", "Martin Luther King", "Che Guevara",
    "Christophe Colomb", "Marco Polo", "Magellan",
    "Winston Churchill", "Abraham Lincoln", "Charles de Gaulle",
    "Genghis Khan", "Attila", "Hannibal Barca",
  ],
};
