const wordPairs = {
  manga: [
    { citizens: "Goku", undercover: "Vegeta" },
    { citizens: "Gohan", undercover: "Goten" },
    { citizens: "Piccolo", undercover: "Freezer" },
    { citizens: "Boo", undercover: "Cell" },
    { citizens: "Krilin", undercover: "Yamcha" },
    { citizens: "Naruto", undercover: "Sasuke" },
    { citizens: "Sakura", undercover: "Hinata" },
    { citizens: "Kakashi", undercover: "Iruka" },
    { citizens: "Itachi", undercover: "Madara" },
    { citizens: "Minato", undercover: "Kushina" },
    { citizens: "Gaara", undercover: "Rock Lee" },
    { citizens: "Jiraiya", undercover: "Tsunade" },
    { citizens: "Luffy", undercover: "Zoro" },
    { citizens: "Sanji", undercover: "Nami" },
    { citizens: "Ace", undercover: "Sabo" },
    { citizens: "Shanks", undercover: "Barbe Blanche" },
    { citizens: "Kaido", undercover: "Big Mom" },
    { citizens: "Doflamingo", undercover: "Crocodile" },
    { citizens: "Ichigo", undercover: "Rukia" },
    { citizens: "Aizen", undercover: "Urahara" },
    { citizens: "Byakuya", undercover: "Kenpachi" },
    { citizens: "Eren", undercover: "Mikasa" },
    { citizens: "Levi", undercover: "Erwin" },
    { citizens: "Reiner", undercover: "Bertholdt" },
    { citizens: "Tanjiro", undercover: "Zenitsu" },
    { citizens: "Rengoku", undercover: "Tengen" },
    { citizens: "Deku", undercover: "Bakugo" },
    { citizens: "Todoroki", undercover: "Iida" },
    { citizens: "All Might", undercover: "Endeavor" },
    { citizens: "Gojo", undercover: "Geto" },
    { citizens: "Itadori", undercover: "Megumi" },
    { citizens: "Gon", undercover: "Killua" },
    { citizens: "Hisoka", undercover: "Illumi" },
    { citizens: "Edward Elric", undercover: "Alphonse Elric" },
    { citizens: "Light", undercover: "L" },
    { citizens: "Saitama", undercover: "Genos" },
    { citizens: "Pikachu", undercover: "Evoli" },
    { citizens: "Mewtwo", undercover: "Mew" },
    { citizens: "Ash", undercover: "Gary" },
    { citizens: "Rasengan", undercover: "Chidori" },
    { citizens: "Kamehameha", undercover: "Big Bang Attack" },
    { citizens: "Bankai", undercover: "Shikai" },
    { citizens: "Super Saiyan", undercover: "Super Saiyan 2" },
    { citizens: "Sharingan", undercover: "Byakugan" },
    { citizens: "One For All", undercover: "All For One" },
    { citizens: "Dragon Ball Z", undercover: "Dragon Ball Super" },
    { citizens: "Demon Slayer", undercover: "Jujutsu Kaisen" },
    { citizens: "Attack on Titan", undercover: "Vinland Saga" },
    { citizens: "Fullmetal Alchemist", undercover: "Soul Eater" },
    { citizens: "Re:Zero", undercover: "KonoSuba" },
  ],

  cinema: [
    { citizens: "Titanic", undercover: "Avatar" },
    { citizens: "Star Wars", undercover: "Star Trek" },
    { citizens: "Inception", undercover: "Interstellar" },
    { citizens: "Le Parrain", undercover: "Scarface" },
    { citizens: "Pulp Fiction", undercover: "Reservoir Dogs" },
    { citizens: "Matrix", undercover: "Terminator" },
    { citizens: "Forrest Gump", undercover: "Cast Away" },
    { citizens: "Joker", undercover: "Batman" },
    { citizens: "Iron Man", undercover: "Thor" },
    { citizens: "Avengers", undercover: "Justice League" },
    { citizens: "Harry Potter", undercover: "Le Seigneur des Anneaux" },
    { citizens: "Indiana Jones", undercover: "Lara Croft" },
    { citizens: "James Bond", undercover: "Mission Impossible" },
    { citizens: "Alien", undercover: "Predator" },
    { citizens: "Jurassic Park", undercover: "Le Monde Perdu" },
    { citizens: "Leonardo DiCaprio", undercover: "Brad Pitt" },
    { citizens: "Tom Hanks", undercover: "Tom Cruise" },
    { citizens: "Spielberg", undercover: "Nolan" },
    { citizens: "Kubrick", undercover: "Scorsese" },
    { citizens: "Pixar", undercover: "DreamWorks" },
    { citizens: "Oscars", undercover: "Cesar" },
    { citizens: "Cannes", undercover: "Venise" },
    { citizens: "Voldemort", undercover: "Dumbledore" },
    { citizens: "Darth Vader", undercover: "Luke Skywalker" },
    { citizens: "Gladiator", undercover: "Braveheart" },
  ],

  geographie: [
    { citizens: "Paris", undercover: "Lyon" },
    { citizens: "Tokyo", undercover: "Osaka" },
    { citizens: "New York", undercover: "Los Angeles" },
    { citizens: "Londres", undercover: "Manchester" },
    { citizens: "Rome", undercover: "Milan" },
    { citizens: "Madrid", undercover: "Barcelone" },
    { citizens: "Amazone", undercover: "Nil" },
    { citizens: "Everest", undercover: "K2" },
    { citizens: "Sahara", undercover: "Gobi" },
    { citizens: "Pacifique", undercover: "Atlantique" },
    { citizens: "Bresil", undercover: "Argentine" },
    { citizens: "Chine", undercover: "Japon" },
    { citizens: "Espagne", undercover: "Portugal" },
    { citizens: "Australie", undercover: "Nouvelle-Zelande" },
    { citizens: "Canada", undercover: "Etats-Unis" },
    { citizens: "Tour Eiffel", undercover: "Arc de Triomphe" },
    { citizens: "Grande Muraille", undercover: "Muraille d'Hadrien" },
    { citizens: "Pyramides", undercover: "Sphinx" },
    { citizens: "Colisee", undercover: "Pantheon" },
    { citizens: "Himalaya", undercover: "Alpes" },
    { citizens: "Mediterranee", undercover: "Mer Rouge" },
    { citizens: "Vatican", undercover: "Monaco" },
    { citizens: "Islande", undercover: "Norvege" },
    { citizens: "Dubai", undercover: "Abu Dhabi" },
    { citizens: "Moscou", undercover: "Saint-Petersbourg" },
  ],

  personnalites: [
    { citizens: "Elon Musk", undercover: "Jeff Bezos" },
    { citizens: "Steve Jobs", undercover: "Bill Gates" },
    { citizens: "Mark Zuckerberg", undercover: "Jack Dorsey" },
    { citizens: "Picasso", undercover: "Van Gogh" },
    { citizens: "Leonardo da Vinci", undercover: "Michel-Ange" },
    { citizens: "Shakespeare", undercover: "Victor Hugo" },
    { citizens: "Voltaire", undercover: "Rousseau" },
    { citizens: "Marilyn Monroe", undercover: "Audrey Hepburn" },
    { citizens: "Martin Luther King", undercover: "Malcolm X" },
    { citizens: "Gandhi", undercover: "Mandela" },
    { citizens: "Barack Obama", undercover: "Joe Biden" },
    { citizens: "Charlie Chaplin", undercover: "Buster Keaton" },
    { citizens: "Salvador Dali", undercover: "Frida Kahlo" },
    { citizens: "Dostoievski", undercover: "Tolstoi" },
    { citizens: "Hemingway", undercover: "Fitzgerald" },
    { citizens: "Warren Buffett", undercover: "George Soros" },
    { citizens: "Freud", undercover: "Jung" },
    { citizens: "Platon", undercover: "Aristote" },
    { citizens: "Karl Marx", undercover: "Friedrich Engels" },
    { citizens: "Copernic", undercover: "Galilee" },
  ],

  histoire: [
    { citizens: "Napoleon Bonaparte", undercover: "Wellington" },
    { citizens: "Jules Cesar", undercover: "Auguste" },
    { citizens: "Cleopatre", undercover: "Nefertiti" },
    { citizens: "Alexandre le Grand", undercover: "Gengis Khan" },
    { citizens: "Christophe Colomb", undercover: "Vasco de Gama" },
    { citizens: "Louis XIV", undercover: "Louis XVI" },
    { citizens: "Charlemagne", undercover: "Pepin le Bref" },
    { citizens: "Jeanne d'Arc", undercover: "Catherine de Medicis" },
    { citizens: "Revolution francaise", undercover: "Revolution americaine" },
    { citizens: "Premiere Guerre mondiale", undercover: "Seconde Guerre mondiale" },
    { citizens: "D-Day", undercover: "Bataille de Verdun" },
    { citizens: "Empire romain", undercover: "Empire grec" },
    { citizens: "Moyen Age", undercover: "Renaissance" },
    { citizens: "Versailles", undercover: "Fontainebleau" },
    { citizens: "Guerre froide", undercover: "Course aux armements" },
    { citizens: "Mur de Berlin", undercover: "Rideau de fer" },
    { citizens: "Croisades", undercover: "Reconquista" },
    { citizens: "Revolution industrielle", undercover: "Revolution agricole" },
    { citizens: "Marie-Antoinette", undercover: "Marie de Medicis" },
    { citizens: "Magellan", undercover: "Christophe Colomb" },
  ],

  jeuxvideo: [
    { citizens: "Mario", undercover: "Luigi" },
    { citizens: "Link", undercover: "Zelda" },
    { citizens: "Sonic", undercover: "Tails" },
    { citizens: "Master Chief", undercover: "Marcus Fenix" },
    { citizens: "Kratos", undercover: "Dante" },
    { citizens: "Cloud Strife", undercover: "Sephiroth" },
    { citizens: "Lara Croft", undercover: "Nathan Drake" },
    { citizens: "Solid Snake", undercover: "Sam Fisher" },
    { citizens: "Geralt de Riv", undercover: "Arthur Morgan" },
    { citizens: "Minecraft", undercover: "Terraria" },
    { citizens: "Fortnite", undercover: "Warzone" },
    { citizens: "League of Legends", undercover: "Dota 2" },
    { citizens: "FIFA", undercover: "PES" },
    { citizens: "GTA", undercover: "Red Dead Redemption" },
    { citizens: "Dark Souls", undercover: "Elden Ring" },
    { citizens: "God of War", undercover: "Assassin's Creed" },
    { citizens: "PlayStation", undercover: "Xbox" },
    { citizens: "Nintendo Switch", undercover: "Steam Deck" },
    { citizens: "Counter-Strike", undercover: "Valorant" },
    { citizens: "The Last of Us", undercover: "Uncharted" },
    { citizens: "Resident Evil", undercover: "Silent Hill" },
    { citizens: "Pac-Man", undercover: "Donkey Kong" },
    { citizens: "Tetris", undercover: "Pong" },
    { citizens: "Skyrim", undercover: "Oblivion" },
    { citizens: "World of Warcraft", undercover: "Final Fantasy XIV" },
  ],

  gastronomie: [
    { citizens: "Pizza", undercover: "Calzone" },
    { citizens: "Sushi", undercover: "Sashimi" },
    { citizens: "Burger", undercover: "Hot Dog" },
    { citizens: "Croissant", undercover: "Pain au chocolat" },
    { citizens: "Camembert", undercover: "Brie" },
    { citizens: "Champagne", undercover: "Prosecco" },
    { citizens: "Bordeaux", undercover: "Bourgogne" },
    { citizens: "Tiramisu", undercover: "Panna cotta" },
    { citizens: "Crepe", undercover: "Gaufre" },
    { citizens: "Ratatouille", undercover: "Bouillabaisse" },
    { citizens: "Baguette", undercover: "Ficelle" },
    { citizens: "Macarons", undercover: "Eclairs" },
    { citizens: "Steak", undercover: "Cotelette" },
    { citizens: "Tacos", undercover: "Burrito" },
    { citizens: "Pates", undercover: "Risotto" },
    { citizens: "Escargots", undercover: "Cuisses de grenouilles" },
    { citizens: "Foie gras", undercover: "Pate" },
    { citizens: "Homard", undercover: "Langouste" },
    { citizens: "Coq au vin", undercover: "Boeuf bourguignon" },
    { citizens: "Mousse au chocolat", undercover: "Creme brulee" },
    { citizens: "Fromage", undercover: "Yaourt" },
    { citizens: "Tarte Tatin", undercover: "Clafoutis" },
    { citizens: "Raclette", undercover: "Fondue" },
    { citizens: "Madeleine", undercover: "Financier" },
    { citizens: "Soupe a l'oignon", undercover: "Vichyssoise" },
  ],

  musique: [
    { citizens: "Michael Jackson", undercover: "Prince" },
    { citizens: "Beatles", undercover: "Rolling Stones" },
    { citizens: "Elvis Presley", undercover: "Chuck Berry" },
    { citizens: "Madonna", undercover: "Britney Spears" },
    { citizens: "Beyonce", undercover: "Rihanna" },
    { citizens: "Taylor Swift", undercover: "Ariana Grande" },
    { citizens: "Eminem", undercover: "Jay-Z" },
    { citizens: "Kanye West", undercover: "Drake" },
    { citizens: "Daft Punk", undercover: "Justice" },
    { citizens: "Stromae", undercover: "Angele" },
    { citizens: "Bob Marley", undercover: "Peter Tosh" },
    { citizens: "Nirvana", undercover: "Pearl Jam" },
    { citizens: "AC/DC", undercover: "Metallica" },
    { citizens: "Mozart", undercover: "Beethoven" },
    { citizens: "Bach", undercover: "Vivaldi" },
    { citizens: "David Bowie", undercover: "Freddie Mercury" },
    { citizens: "Rap", undercover: "R&B" },
    { citizens: "Jazz", undercover: "Blues" },
    { citizens: "Rock", undercover: "Metal" },
    { citizens: "Guitare", undercover: "Basse" },
    { citizens: "Piano", undercover: "Violon" },
    { citizens: "Spotify", undercover: "Apple Music" },
    { citizens: "Woodstock", undercover: "Coachella" },
    { citizens: "Pink Floyd", undercover: "Led Zeppelin" },
    { citizens: "Sinatra", undercover: "Dean Martin" },
  ],

  sport: [
    { citizens: "Football", undercover: "Rugby" },
    { citizens: "Tennis", undercover: "Badminton" },
    { citizens: "Messi", undercover: "Ronaldo" },
    { citizens: "Federer", undercover: "Nadal" },
    { citizens: "Djokovic", undercover: "Murray" },
    { citizens: "Mbappe", undercover: "Neymar" },
    { citizens: "LeBron James", undercover: "Stephen Curry" },
    { citizens: "Michael Jordan", undercover: "Kobe Bryant" },
    { citizens: "Serena Williams", undercover: "Venus Williams" },
    { citizens: "Usain Bolt", undercover: "Carl Lewis" },
    { citizens: "Michael Phelps", undercover: "Ryan Lochte" },
    { citizens: "Real Madrid", undercover: "FC Barcelone" },
    { citizens: "PSG", undercover: "Olympique de Marseille" },
    { citizens: "Manchester United", undercover: "Manchester City" },
    { citizens: "Formule 1", undercover: "MotoGP" },
    { citizens: "Hamilton", undercover: "Verstappen" },
    { citizens: "Tour de France", undercover: "Giro d'Italia" },
    { citizens: "Roland Garros", undercover: "Wimbledon" },
    { citizens: "NBA", undercover: "NFL" },
    { citizens: "Jeux Olympiques", undercover: "Jeux Paralympiques" },
    { citizens: "Coupe du Monde", undercover: "Euro" },
    { citizens: "Ali", undercover: "Tyson" },
    { citizens: "Schumacher", undercover: "Senna" },
    { citizens: "Zidane", undercover: "Ronaldinho" },
    { citizens: "Natation", undercover: "Plongeon" },
  ],

  science: [
    { citizens: "Einstein", undercover: "Newton" },
    { citizens: "Darwin", undercover: "Mendel" },
    { citizens: "Marie Curie", undercover: "Louis Pasteur" },
    { citizens: "Hawking", undercover: "Feynman" },
    { citizens: "ADN", undercover: "ARN" },
    { citizens: "Atome", undercover: "Molecule" },
    { citizens: "Gravitation", undercover: "Electromagnetisme" },
    { citizens: "Trou noir", undercover: "Etoile a neutrons" },
    { citizens: "Big Bang", undercover: "Inflation cosmique" },
    { citizens: "Relativite", undercover: "Mecanique quantique" },
    { citizens: "Mars", undercover: "Venus" },
    { citizens: "Jupiter", undercover: "Saturne" },
    { citizens: "Planete", undercover: "Etoile" },
    { citizens: "Oxygene", undercover: "Azote" },
    { citizens: "Hydrogene", undercover: "Helium" },
    { citizens: "Photosynthese", undercover: "Respiration cellulaire" },
    { citizens: "Virus", undercover: "Bacterie" },
    { citizens: "Vaccin", undercover: "Antibiotique" },
    { citizens: "Intelligence artificielle", undercover: "Machine learning" },
    { citizens: "Fusion nucleaire", undercover: "Fission nucleaire" },
    { citizens: "Electron", undercover: "Proton" },
    { citizens: "CRISPR", undercover: "Sequencage genomique" },
    { citizens: "Cerveau", undercover: "Systeme nerveux" },
    { citizens: "Comete", undercover: "Asteroide" },
    { citizens: "Trou de ver", undercover: "Dimension parallele" },
  ],
};

module.exports = wordPairs;
